### ISSUE TITLE
 bundle exec issue during installation

### ISSUE THREAD

**Issue by y2mq37** [EFForg/congress-forms#56]
Running into an error during the installation step listed below:
```
bundle exec rake congress-forms:update_git[contact_congress_directory]
```
I'm receiving this printout:
```
root@REDACTED:/var/www/html/congress-forms-master# bundle exec rake congress-forms:update_git[/var/www/html/congress-forms-master/contact-congress] --trace
** Invoke congress-forms:update_git (first_time)
** Execute congress-forms:update_git
  DEBUG -  Application Load (1.8ms)  SELECT `application_settings`.* FROM `application_settings` WHERE `application_settings`.`key` = 'contact_congress_commit' LIMIT 1
No previous commit found, reloading all congress members into db
rake aborted!
NoMethodError: undefined method `[]' for false:FalseClass
tasks/congress-forms.rake:320:in `block (2 levels) in update_db_with_git_object'
tasks/congress-forms.rake:335:in `create_congress_member_exception_wrapper'
tasks/congress-forms.rake:317:in `block in update_db_with_git_object'
tasks/congress-forms.rake:315:in `each'
tasks/congress-forms.rake:315:in `update_db_with_git_object'
tasks/congress-forms.rake:183:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => congress-forms:update_git
```

**Comment by Hainish** [comment]
Hey @y2mq37, are you pointing this at an actual contact congress directory?
https://github.com/EFForg/congress-forms#populating-the-database

**Comment by y2mq37** [comment]
yes, [contact_congress_directory], was pointed at the /contact-congress directory. I ended up pasting an older table into the database for developmental purposes, but I'll need to import a newer release soon anyways. I'll let you know if I run into this issue again.
