### ISSUE TITLE
NoMethodError during congress-forms:update_git rake task

### ISSUE THREAD

**Issue by bglazer** [EFForg/congress-forms#63]
When running the following command:
bundle exec rake congress-forms:update_git[../contact-congress]

I get the following error:
```
NoMethodError: undefined method `number_of_candidates=' for #<SmartyStreets::Configuration:0x00000002b40170>
/home/ubuntu/congress-forms/config/boot.rb:25:in `block in <top (required)>'
```

Simply commenting out boot.rb line 25 solves the problem for me and the tests still pass without this line. That's not to say it won't break anything else, but I haven't encountered issues yet, as I'm still in the setup phase.

The stack trace is below:

```
NoMethodError: undefined method `number_of_candidates=' for #<SmartyStreets::Configuration:0x00000002b40170>
/home/ubuntu/congress-forms/config/boot.rb:25:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/smarty_streets-0.0.4/lib/smarty_streets.rb:22:in `configure'
/home/ubuntu/congress-forms/config/boot.rb:22:in `<top (required)>'
tasks/congress-forms.rake:1:in `require'
tasks/congress-forms.rake:1:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/padrino-core-0.11.4/lib/padrino-core/cli/rake_tasks.rb:3:in `load'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/padrino-core-0.11.4/lib/padrino-core/cli/rake_tasks.rb:3:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/padrino-core-0.11.4/lib/padrino-core/cli/rake_tasks.rb:1:in `each'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/padrino-core-0.11.4/lib/padrino-core/cli/rake_tasks.rb:1:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/padrino-core-0.11.4/lib/padrino-core/cli/rake.rb:12:in `load'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/gems/padrino-core-0.11.4/lib/padrino-core/cli/rake.rb:12:in `init'
/home/ubuntu/congress-forms/Rakefile:6:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.1.0@congress-forms/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by Hainish** [comment]
Hey @bglazer
Looks like your version of `smarty_streets` is more recent than the one specified in `Gemfile.lock`, this is causing the problem.

**Comment by Hainish** [comment]
I've updated to the latest gems as of https://github.com/EFForg/congress-forms/commit/86e27bdd4dbf761db6040b5d1abb6cc6cb65c4ab, this problem should be fixed now
